apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
  tags:
    - java
spec:
  type: website
  lifecycle: experimental
  owner: john@example.com
